import { GeneratedScene, SVGElementData, SVGPathElementData, SVGCircleElementData, SVGPolygonElementData } from "../types/geometry";
import { JantraRecipe } from "../types/recipe";
import { PreflightDiagnostic } from "../types/export";

function round3(n: number): number {
  return Math.round(n * 1000) / 1000;
}

function serializeElement(
  el: SVGElementData,
  minified = false,
  plotterMode = false
): string {
  const indent = minified ? "" : "    ";
  const nl = minified ? "" : "\n";

  if ("d" in el) {
    const p = el as SVGPathElementData;
    let attrs = `id="${p.id}" d="${p.d}"`;
    if (plotterMode) {
      attrs += ` stroke="#000000" stroke-width="0.3" fill="none"`;
    } else {
      if (p.stroke) attrs += ` stroke="${p.stroke}"`;
      if (p.strokeWidth !== undefined) attrs += ` stroke-width="${round3(p.strokeWidth)}"`;
      if (p.strokeLinecap) attrs += ` stroke-linecap="${p.strokeLinecap}"`;
      if (p.strokeLinejoin) attrs += ` stroke-linejoin="${p.strokeLinejoin}"`;
      if (p.strokeDasharray) attrs += ` stroke-dasharray="${p.strokeDasharray}"`;
      if (p.strokeOpacity !== undefined) attrs += ` stroke-opacity="${round3(p.strokeOpacity)}"`;
      attrs += ` fill="${p.fill || "none"}"`;
      if (p.fillOpacity !== undefined) attrs += ` fill-opacity="${round3(p.fillOpacity)}"`;
      if (p.opacity !== undefined) attrs += ` opacity="${round3(p.opacity)}"`;
    }

    return `${indent}<path ${attrs} />${nl}`;
  } else if ("r" in el) {
    const c = el as SVGCircleElementData;
    let attrs = `id="${c.id}" cx="${c.cx}" cy="${c.cy}" r="${c.r}"`;
    if (plotterMode) {
      attrs += ` stroke="#000000" stroke-width="0.3" fill="none"`;
    } else {
      if (c.stroke) attrs += ` stroke="${c.stroke}"`;
      if (c.strokeWidth !== undefined) attrs += ` stroke-width="${round3(c.strokeWidth)}"`;
      if (c.strokeDasharray) attrs += ` stroke-dasharray="${c.strokeDasharray}"`;
      if (c.strokeOpacity !== undefined) attrs += ` stroke-opacity="${round3(c.strokeOpacity)}"`;
      attrs += ` fill="${c.fill || "none"}"`;
      if (c.fillOpacity !== undefined) attrs += ` fill-opacity="${round3(c.fillOpacity)}"`;
      if (c.opacity !== undefined) attrs += ` opacity="${round3(c.opacity)}"`;
    }

    return `${indent}<circle ${attrs} />${nl}`;
  } else if ("points" in el) {
    const poly = el as SVGPolygonElementData;
    let attrs = `id="${poly.id}" points="${poly.points}"`;
    if (plotterMode) {
      attrs += ` stroke="#000000" stroke-width="0.3" fill="none"`;
    } else {
      if (poly.stroke) attrs += ` stroke="${poly.stroke}"`;
      if (poly.strokeWidth !== undefined) attrs += ` stroke-width="${round3(poly.strokeWidth)}"`;
      if (poly.strokeOpacity !== undefined) attrs += ` stroke-opacity="${round3(poly.strokeOpacity)}"`;
      attrs += ` fill="${poly.fill || "none"}"`;
      if (poly.fillOpacity !== undefined) attrs += ` fill-opacity="${round3(poly.fillOpacity)}"`;
    }

    return `${indent}<polygon ${attrs} />${nl}`;
  }
  return "";
}

export function serializeSceneToSVG(
  scene: GeneratedScene,
  recipe: JantraRecipe,
  options: {
    minified?: boolean;
    includeMetadata?: boolean;
    animated?: boolean;
    plotterMode?: boolean;
  } = {}
): string {
  const { minified = false, includeMetadata = true, animated = false, plotterMode = false } = options;
  const nl = minified ? "" : "\n";
  const indent = minified ? "" : "  ";

  let svg = `<?xml version="1.0" encoding="UTF-8"?>${nl}`;
  svg += `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `viewBox="${scene.viewBox}" ` +
    `width="${scene.width}" ` +
    `height="${scene.height}" ` +
    `data-jantra-schema="${recipe.schemaVersion}" ` +
    `data-jantra-engine="${recipe.engineVersion}" ` +
    `data-jantra-seed="${recipe.seed}" ` +
    `data-jantra-grammar="${recipe.grammar.id}"` +
    `>${nl}`;

  // If animated SVG, inject CSS keyframe drawing animation
  if (animated) {
    svg += `${indent}<style>${nl}`;
    svg += `${indent}  @keyframes jantraDraw {${nl}`;
    svg += `${indent}    0% { stroke-dashoffset: 1500; opacity: 0; }${nl}`;
    svg += `${indent}    15% { opacity: 1; }${nl}`;
    svg += `${indent}    100% { stroke-dashoffset: 0; opacity: 1; }${nl}`;
    svg += `${indent}  }${nl}`;
    svg += `${indent}  @keyframes jantraPulse {${nl}`;
    svg += `${indent}    0%, 100% { transform: scale(1); }${nl}`;
    svg += `${indent}    50% { transform: scale(1.08); }${nl}`;
    svg += `${indent}  }${nl}`;
    svg += `${indent}  path, circle, polygon {${nl}`;
    svg += `${indent}    stroke-dasharray: 1500;${nl}`;
    svg += `${indent}    animation: jantraDraw 3.5s cubic-bezier(0.4, 0, 0.2, 1) forwards;${nl}`;
    svg += `${indent}  }${nl}`;
    svg += `${indent}  #jantra-bindu-center { animation: jantraPulse 4s ease-in-out infinite; transform-origin: center; }${nl}`;
    svg += `${indent}</style>${nl}`;
  }

  if (includeMetadata && !minified) {
    svg += `${indent}<!-- Generated by JANTRA (यन्त्र) — Generative Indian Visual Intelligence Engine -->${nl}`;
    svg += `${indent}<!-- Seed: ${recipe.seed} | Engine: ${recipe.engineVersion} | Mode: ${plotterMode ? "Pen Plotter (Single-Stroke)" : "Figma Layered Vectors"} -->${nl}`;
    svg += `${indent}<metadata>${nl}`;
    svg += `${indent}  <jantra:recipe xmlns:jantra="https://jantra.design/schema/1.0">${nl}`;
    svg += `${indent}    ${JSON.stringify(recipe, null, 2).replace(/\n/g, `\n${indent}    `)}${nl}`;
    svg += `${indent}  </jantra:recipe>${nl}`;
    svg += `${indent}</metadata>${nl}`;
  }

  // Render each semantic group
  for (const group of scene.groups) {
    if (group.elements.length === 0) continue;
    if (plotterMode && group.id === "jantra-background") continue; // Exclude solid background fill in plotter mode

    svg += `${indent}<g id="${group.id}" data-name="${group.name}">${nl}`;
    for (const el of group.elements) {
      svg += serializeElement(el, minified, plotterMode);
    }
    svg += `${indent}</g>${nl}`;
  }

  svg += `</svg>`;
  return svg;
}

export function computePreflightDiagnostics(scene: GeneratedScene, svgString: string): PreflightDiagnostic {
  const layerGroups = scene.groups.map(g => g.id);
  const sizeBytes = new Blob([svgString]).size;
  const estimatedFileSizeKB = Math.round((sizeBytes / 1024) * 10) / 10;

  const hasForeignObjects = svgString.includes("<foreignObject");
  const hasScripts = svgString.includes("<script");
  const hasExternalDependencies = svgString.includes("<image") || svgString.includes("@import") || svgString.includes("href=\"http");

  const figmaCompatible = !hasForeignObjects && !hasScripts && !hasExternalDependencies && layerGroups.length > 0;

  return {
    pathCount: scene.totalPaths,
    vertexCount: scene.totalVertices,
    estimatedFileSizeKB,
    viewBox: scene.viewBox,
    hasForeignObjects,
    hasScripts,
    hasExternalDependencies,
    figmaCompatible,
    illustratorCompatible: figmaCompatible,
    inkscapeCompatible: figmaCompatible,
    plotterReady: figmaCompatible,
    layerGroups,
  };
}
