import { JantraRecipe, PresetRecipe } from "../types/recipe";

export const defaultRecipe: JantraRecipe = {
  schemaVersion: "1.0",
  engineVersion: "0.1.0",
  grammar: {
    id: "geometric-radial",
    version: "0.1.0",
  },
  seed: "108",
  canvas: {
    width: 1600,
    height: 1600,
    background: "#09090b",
    margin: 0.08,
  },
  parameters: {
    symmetry: {
      mode: "radial",
      segments: 8,
    },
    rings: {
      count: 5,
      spacing: "harmonic",
      showGuideLines: false,
    },
    recursion: {
      depth: 3,
      scale: 0.65,
    },
    density: 0.35,
    prana: 0.06,
    line: {
      weight: 1.4,
      cap: "round",
      color: "#f4f4f5",
      dashPattern: "none",
    },
    motifs: {
      primary: "lotus_lobe",
      secondary: "dot",
      bindu: {
        radius: 8,
        style: "radiant",
      },
      bhupura: {
        enabled: true,
        gates: 4,
        steps: 2,
        finials: true,
      },
    },
    palette: {
      stroke: "#f4f4f5",
      secondaryStroke: "#71717a",
      accent: "#f59e0b",
      fill: "none",
    },
  },
  provenance: {
    aiInterpreted: false,
    promptText: "Default sacred lotus composition with harmonic radial rings and stepped bhupura",
    createdAt: new Date().toISOString(),
  },
};

export const PRESETS: PresetRecipe[] = [
  {
    id: "sri-yantra",
    name: "Sri Yantra Mahameru",
    sanskritName: "श्री यन्त्र",
    description: "The supreme archetype of sacred geometry: 9 interlocking Shiva & Shakti triangles forming 43 sub-triangles, nested 8 and 16-petal lotus tiers, and a 3-tier stepped earth citadel.",
    category: "sacred",
    recipe: {
      ...defaultRecipe,
      seed: "108",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 8 },
        rings: { count: 6, spacing: "harmonic", showGuideLines: false },
        recursion: { depth: 4, scale: 0.7 },
        density: 0.45,
        prana: 0.03,
        line: { weight: 1.3, cap: "round", color: "#fef3c7" },
        motifs: {
          primary: "sri_yantra",
          secondary: "dot",
          bindu: { radius: 6, style: "solid" },
          bhupura: { enabled: true, gates: 4, steps: 3, finials: true },
        },
        palette: {
          stroke: "#fef3c7",
          accent: "#f59e0b",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Sri Yantra Mahameru Archetype",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "ashta-padma",
    name: "Ashta Padma (8-Fold Lotus)",
    sanskritName: "अष्टदल पद्म",
    description: "Multi-tiered parametric lotus petals with harmonic radial progression and radiant solar bindu origin.",
    category: "floral",
    recipe: {
      ...defaultRecipe,
      seed: "1008",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 8 },
        rings: { count: 5, spacing: "harmonic", showGuideLines: false },
        recursion: { depth: 3, scale: 0.65 },
        density: 0.38,
        prana: 0.05,
        line: { weight: 1.4, cap: "round", color: "#f5f5f7" },
        motifs: {
          primary: "lotus_double",
          secondary: "circle",
          bindu: { radius: 10, style: "radiant" },
          bhupura: { enabled: true, gates: 4, steps: 2, finials: true },
        },
        palette: {
          stroke: "#f5f5f7",
          accent: "#fbbf24",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Ashta Padma 8-fold lotus",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "sahasrara-crown",
    name: "Sahasrara (Crown Chakra)",
    sanskritName: "सहस्रार चक्र",
    description: "Dense 32-segment blossoming thousand-petaled lotus with triple concentric radiant aura rings.",
    category: "sacred",
    recipe: {
      ...defaultRecipe,
      seed: "1000",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 32 },
        rings: { count: 7, spacing: "golden", showGuideLines: false },
        recursion: { depth: 4, scale: 0.72 },
        density: 0.62,
        prana: 0.04,
        line: { weight: 1.0, cap: "round", color: "#fdf4ff" },
        motifs: {
          primary: "lotus_pointed",
          secondary: "dot",
          bindu: { radius: 12, style: "triple_aura" },
          bhupura: { enabled: false, gates: 4, steps: 1 },
        },
        palette: {
          stroke: "#fdf4ff",
          accent: "#e879f9",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Sahasrara 32-segment crown lotus",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "sikku-kolam",
    name: "Brahma Mudi Sikku Kolam",
    sanskritName: "ब्रह्म मुडि कोलम",
    description: "Continuous South Indian threshold knotwork weaving unbroken symmetrical loops around concentric radial pulli dots.",
    category: "kolam",
    recipe: {
      ...defaultRecipe,
      seed: "777",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 8 },
        rings: { count: 4, spacing: "linear", showGuideLines: false },
        recursion: { depth: 2, scale: 0.6 },
        density: 0.45,
        prana: 0.12,
        line: { weight: 1.8, cap: "round", color: "#fef08a" },
        motifs: {
          primary: "kolam_knot",
          secondary: "dot",
          bindu: { radius: 8, style: "solid" },
          bhupura: { enabled: false, gates: 4, steps: 1 },
        },
        palette: {
          stroke: "#fef08a",
          accent: "#f97316",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Brahma Mudi Sikku Kolam continuous loop",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "surya-mandala",
    name: "Surya Mandala (Modhera Sun Temple)",
    sanskritName: "सूर्य मण्डल",
    description: "12-segment radiating solar vectors inspired by the Sun Temple at Modhera with nested star polygons and high-density perimeter ticks.",
    category: "archetype",
    recipe: {
      ...defaultRecipe,
      seed: "432",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 12 },
        rings: { count: 7, spacing: "exponential", showGuideLines: true },
        recursion: { depth: 4, scale: 0.62 },
        density: 0.65,
        prana: 0.04,
        line: { weight: 1.2, cap: "round", color: "#fde68a" },
        motifs: {
          primary: "star",
          secondary: "flame",
          bindu: { radius: 14, style: "radiant" },
          bhupura: { enabled: false, gates: 4, steps: 1 },
        },
        palette: {
          stroke: "#fde68a",
          accent: "#f59e0b",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Surya Mandala Solar Radiance",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "cosmic-shatkona",
    name: "Cosmic Shatkona (6-Fold Hexagram)",
    sanskritName: "षट्कोण यन्त्र",
    description: "Geometric union of Shiva and Shakti upward and downward equilateral triangles with nested harmonic rings and cardinal spokes.",
    category: "sacred",
    recipe: {
      ...defaultRecipe,
      seed: "360",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 6 },
        rings: { count: 4, spacing: "harmonic", showGuideLines: true },
        recursion: { depth: 3, scale: 0.68 },
        density: 0.32,
        prana: 0.02,
        line: { weight: 1.5, cap: "round", color: "#e0f2fe" },
        motifs: {
          primary: "triangle",
          secondary: "cross",
          bindu: { radius: 7, style: "hollow" },
          bhupura: { enabled: true, gates: 4, steps: 2, finials: true },
        },
        palette: {
          stroke: "#e0f2fe",
          accent: "#38bdf8",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Cosmic Shatkona 6-fold hexagram",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "navagraha-orbit",
    name: "Navagraha (9 Planetary Orbits)",
    sanskritName: "नवग्रह मण्डल",
    description: "9-fold sacred planetary geometry with Fibonacci golden ratio rings and teardrop radiance.",
    category: "archetype",
    recipe: {
      ...defaultRecipe,
      seed: "999",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 9 },
        rings: { count: 6, spacing: "golden", showGuideLines: true },
        recursion: { depth: 3, scale: 0.68 },
        density: 0.42,
        prana: 0.04,
        line: { weight: 1.3, cap: "round", color: "#fef08a" },
        motifs: {
          primary: "lotus_pointed",
          secondary: "teardrop",
          bindu: { radius: 11, style: "triple_aura" },
          bhupura: { enabled: true, gates: 4, steps: 2, finials: true },
        },
        palette: {
          stroke: "#fef08a",
          accent: "#f59e0b",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Navagraha 9 planetary orbits",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "anahata-heart",
    name: "Anahata (Heart Chakra)",
    sanskritName: "अनाहत चक्र",
    description: "12-petaled emerald lotus enclosing the intersecting upward (masculine) and downward (feminine) triangles.",
    category: "sacred",
    recipe: {
      ...defaultRecipe,
      seed: "1212",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 12 },
        rings: { count: 5, spacing: "harmonic", showGuideLines: false },
        recursion: { depth: 3, scale: 0.65 },
        density: 0.35,
        prana: 0.05,
        line: { weight: 1.3, cap: "round", color: "#ecfdf5" },
        motifs: {
          primary: "lotus_lobe",
          secondary: "triangle",
          bindu: { radius: 8, style: "radiant" },
          bhupura: { enabled: true, gates: 4, steps: 2, finials: true },
        },
        palette: {
          stroke: "#ecfdf5",
          accent: "#10b981",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Anahata 12-petaled heart chakra",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "architectural-diamond",
    name: "Rajasthani Jali Lattice",
    sanskritName: "जाली विन्यास",
    description: "Crisp 16-segment lozenges and diamond facets with zero prana for pure structural architectural drafting.",
    category: "architectural",
    recipe: {
      ...defaultRecipe,
      seed: "2048",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 16 },
        rings: { count: 6, spacing: "linear", showGuideLines: true },
        recursion: { depth: 4, scale: 0.72 },
        density: 0.52,
        prana: 0.0,
        line: { weight: 1.1, cap: "square", color: "#f5f5f5" },
        motifs: {
          primary: "diamond",
          secondary: "triangle",
          bindu: { radius: 6, style: "hollow" },
          bhupura: { enabled: true, gates: 4, steps: 3, finials: true },
        },
        palette: {
          stroke: "#f5f5f5",
          accent: "#a1a1aa",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Rajasthani Jali Lattice Diamond Grid",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "minimalist-bindu",
    name: "Meditative Bindu Aura",
    sanskritName: "बिन्दु ध्यान",
    description: "Quiet, contemplative minimalism with ultra-clean fine lines and expansive negative space.",
    category: "minimal",
    recipe: {
      ...defaultRecipe,
      seed: "1",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 8 },
        rings: { count: 3, spacing: "exponential", showGuideLines: false },
        recursion: { depth: 1, scale: 0.5 },
        density: 0.12,
        prana: 0.01,
        line: { weight: 0.9, cap: "round", color: "#f4f4f5" },
        motifs: {
          primary: "petal",
          secondary: "none",
          bindu: { radius: 12, style: "radiant" },
          bhupura: { enabled: false, gates: 4, steps: 1 },
        },
        palette: {
          stroke: "#f4f4f5",
          accent: "#e11d48",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Meditative Bindu Aura Minimalist",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
  {
    id: "organic-kolam",
    name: "Vital Kolam (High Prana)",
    sanskritName: "प्राण कोलम",
    description: "Organic, living human imperfection with soft curves, continuous line flow, and traditional threshold rhythm.",
    category: "kolam",
    recipe: {
      ...defaultRecipe,
      seed: "72",
      parameters: {
        ...defaultRecipe.parameters,
        symmetry: { mode: "radial", segments: 8 },
        rings: { count: 4, spacing: "linear", showGuideLines: false },
        recursion: { depth: 2, scale: 0.6 },
        density: 0.28,
        prana: 0.18,
        line: { weight: 2.0, cap: "round", color: "#fef08a" },
        motifs: {
          primary: "petal",
          secondary: "dot",
          bindu: { radius: 8, style: "solid" },
          bhupura: { enabled: false, gates: 4, steps: 1 },
        },
        palette: {
          stroke: "#fef08a",
          accent: "#f97316",
          fill: "none",
        },
      },
      provenance: {
        aiInterpreted: false,
        promptText: "Vital Kolam with living Prana",
        createdAt: "2026-10-02T00:00:00.000Z",
      },
    },
  },
];
